### ISSUE TITLE
Koodikatselmointi

### ISSUE THREAD

**Issue by Echoes13** [PauliNiva/Tetris#1]
_The project was downloaded at 28.05.2015 - 12:35_

The code overall looks nice and clean. The code also follows the Clean Code-principle quite well, which makes understanding the code easier. The comments explaining the methods also make the code that much more understandable. A few things to note:

There has been some talk regarding an object creating another object using itself as the parameter for the newly created object, as somewhat unreliable as it might create an infinite loop at some point if not handled correctly. Personally though, I think it works well here regarding the PlayingField creating its' Mapper. Still, you might want to check up on that.

In the class ForEachCell, is there a need for defining the forEachCell-method with the 2D-int array, as well as the 2D-Object array? I couldn't find the reason, as the two methods are basically identical and int being an (non-directly) extended class from Object.

Lastly, as a minor detail, is the BlockI supposed to be starting more on the left side than the other tetriminoes? Otherwise it could be an idea to move it one step to the right in the tableaux.

As I mentioned in the beginning though, the code looks clean and the tests seem to check the game logic quite well at this point. A few more suitable tests would probably take care of the remaining mutations, especially the ones for enum Direction.

Looks good, keep on developing the gui to make it look awesome!

**Comment by PauliNiva** [comment]
ForEachCell() call in mapper on row 51 needs the int[][] as it cannot be converted or cast to an Object[][]. At least I do not know any means to make do with only object[][]. If you have any suggestions how to get around it, it would be appreciated.

I have not yet decided on the starting positions of the tetriminoes and that is why they start a little here and there so i can observe which position looks better.
